name: test-on-push
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Run tests
        run: hatch test
